#!/bin/bash

# Check if the user provided an argument
if [ $# -eq 0 ]; then
  echo "No user specified. Usage: ./0-iamsomeoneelse.sh <username>"
  exit 1
fi

# Get the username from the argument
USERNAME=$1

# Switch to the specified user and run whoami
su -c "whoami" $USERNAME
